### ISSUE TITLE
php-fpm reload by default

### ISSUE THREAD

**Issue by giannello** [saltstack-formulas/php-formula#12]
The usual workflow with php-fpm is to trigger a reload instead of a restart, to gracefully handle for all the processes to terminate before killing and respawning the children.

Should we change the defaults for the php-fpm service to enforce this behavior?

**Comment by n-rodriguez** [comment]
@myii I think we can close this one

**Comment by myii** [comment]
Closing this since it is a very old report.  Feel free to reopen this if this is still an issue with the latest version of this formula.

@n-rodriguez, thanks for highlighting this.
