### ISSUE TITLE
Wrong package name for php-xdebug

### ISSUE THREAD

**Issue by hackel** [saltstack-formulas/php-formula#131]
I just wanted to run this by someone before submitting a pull request to make sure I'm getting this right.

In map.jinja, `'xdebug': 'php' + phpng_version + '-xdebug'` is used when it should actually be just `php-xdebug`.  It looks like php7.1-xdebug used to exist separately in the ondrej PPA, but no longer.  Now php-xdebug works for 5, 7.0, and 7.1.

This is the case when using the repo for all Ubuntu and Debian versions, or when not using the repo for Ubuntu >= 16.04 and Debian > jessie.  As far as I can tell, php7.1-xdebug is no longer used at all.

**Comment by n-rodriguez** [comment]
Fixed by https://github.com/saltstack-formulas/php-formula/pull/197/commits/496ec28dae41dd244bc77f92d0bfda7927f56563
