### ISSUE TITLE
Provide kitchen tests for php-formula

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack-formulas/php-formula#174]
In a number of saltstack-formulas there are kitchen https://kitchen.ci/ tests to test the code and deployment in sandbox VMs. It would be nice to have such tests on php-formula

**Comment by myii** [comment]
@arthurlogilab Thanks for creating this issue.  For any intrepid contributor looking to take up this task, please base the matrix on either the [`salt-formula`](https://github.com/saltstack-formulas/salt-formula) or the [`template-formula`](https://github.com/saltstack-formulas/template-formula).  These contain the latest, recommended ways to do this.  Both of these will probably be standardised soon -- in that case, the `template-formula` will be the best source for the configuration required.

@javierbertoli Any further opinions about this?

**Comment by myii** [comment]
@arthurlogilab The structure has been introduced by @n-rodriguez in #179.  It's just a matter of adding InSpec tests now.

**Comment by n-rodriguez** [comment]
@myii working on it right now. There is a bug in https://github.com/saltstack-formulas/php-formula/blob/master/php/fpm/pools_config.sls#L21

**Comment by n-rodriguez** [comment]
@myii it would be nice to implement the repo pattern in this formula.

The repo config available in pillars are very specific (centos, ubuntu). The repo pattern would help to configure repos for other distros.

It would also ease testing by setting custom repos in Kitchen. I'm using Debian in production with [php-sury](https://deb.sury.org/) and it does support multiple php install. This way I could install multiple versions of Php and test various configurations. What do you think?

**Comment by n-rodriguez** [comment]
> @myii it would be nice to implement the repo pattern in this formula.

ping @myii

**Comment by myii** [comment]
@n-rodriguez Sounds great, thanks for providing this in #197.
