### ISSUE TITLE
Conflicting ids with the latest release

### ISSUE THREAD

**Issue by n-rodriguez** [saltstack-formulas/php-formula#188]
When I run this formula I got this error :

```sh
[DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/base/php/ng/fpm/install.sls:
include:
  - php.ng.deprecated

# -*- coding: utf-8 -*-
# vim: ft=jinja

include:
  - php.ng.deprecated

php_install_fpm:
  pkg.installed:
    - name: fpm
    - pkgs: ["php7.0-fpm"]

[CRITICAL] Rendering SLS 'base:php.ng.fpm.install' failed: while constructing a mapping
  in "<unicode string>", line 1, column 1
found conflicting ID 'include'
  in "<unicode string>", line 11, column 1
```

My pillars: 

```yml
php:
  ng:
    version:
      - '7.0'
    modules:
      - curl
      - gd
      - mcrypt
      - mysql
```

My state `states/base/install/php.sls` :

```sls
{% set roles = salt['config.get']('jbox_server:roles', []) %}

{% if 'php-server' in roles %}
include:
  - php.ng.fpm.install
  - php.ng.fpm.config
  - php.ng.fpm.pools_config
  - php.ng.modules
  - php.ng.fpm.service
{% endif %}
```
If I quote `php.ng.fpm.install` and `php.ng.fpm.service` it works :

```sls
{% set roles = salt['config.get']('jbox_server:roles', []) %}

{% if 'php-server' in roles %}
include:
  # - php.ng.fpm.install
  - php.ng.fpm.config
  - php.ng.fpm.pools_config
  - php.ng.modules
  # - php.ng.fpm.service
{% endif %}
```

**Comment by myii** [comment]
@n-rodriguez Confirmed with test case: https://travis-ci.org/myii/php-formula/builds/569880654.  The question is, did this work before?  If so, at what point?

**Comment by myii** [comment]
I've repushed that commit in the branch to an earlier commit (08cd563) to see if that still triggers it:

* https://travis-ci.org/myii/php-formula/builds/569888341

**Comment by myii** [comment]
While each run is failing, it's not due the bug reported here, so this bug is something that has been introduced more recently.

As for the failures, they are further bugs to be fixed.

**Comment by myii** [comment]
@n-rodriguez Got a bit of time to look further -- disabling these lines work:

* https://github.com/saltstack-formulas/php-formula/commit/d45bae83d86c624d4fda116c046c59cc13e9dc22#diff-72576bcebd822e41f1e27a9d8a5176cbR1-R3

So it looks like an issue when including alongside `{% include ... %}`.

**Comment by myii** [comment]
@n-rodriguez #189 fixes this as seen here:

* https://travis-ci.org/myii/php-formula/builds/569952658

Please confirm the fix and merge that PR if you're satisfied.

**Comment by n-rodriguez** [comment]
> Please confirm the fix and merge that PR if you're satisfied.

sorry for this late answer but it works :) thank you! :+1:
