### ISSUE TITLE
[BUG] php.composer requires interaction for latest versions

### ISSUE THREAD

**Issue by an0nz** [saltstack-formulas/php-formula#219]
**Describe the bug**
On CentOS 8 and likely other distros with composer 2.0.7+ the php.composer state pauses requiring interaction, you can press enter for it to continue.

**Error Received**
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]?

**Lines causing the issue**
https://github.com/saltstack-formulas/php-formula/blob/b73fffa4b5eec6b7610a47e9053fc13d1877f007/php/composer.sls#L53
https://github.com/saltstack-formulas/php-formula/blob/b73fffa4b5eec6b7610a47e9053fc13d1877f007/php/composer.sls#L55

**Solution**
Add --no-interaction after --version
Alternatively change to a non root user but for this particular command to get the version there is no risk running as root

**Comment by B1ue-W01f** [comment]
Can confirm on Debian too.

**Comment by sticky-note** [comment]
@an0nz 
Thanks for reporting this issue and sharing snippet

https://github.com/saltstack-formulas/php-formula/pull/233 resolves it.
