### ISSUE TITLE
debian php repo improvement

### ISSUE THREAD

**Issue by aboe76** [saltstack-formulas/php-formula#29]
for debian there is an updated repository for php
This repository provides backports to Debian Stable of up to dates versions of the MySql/Php LAMP stack

https://www.dotdeb.org/instructions/

could this be integrated in the php-formula?

**Comment by bogdanr** [comment]
I addressed this one here: https://github.com/saltstack-formulas/php-formula/pull/77

**Comment by gravyboat** [comment]
Closing this since #77 is now merged.
