### ISSUE TITLE
Managing Extensions with php-formula

### ISSUE THREAD

**Issue by RyPeck** [saltstack-formulas/php-formula#35]
Any tips on how to manage extensions with php-formula? Or is that outside the scope of what this should do?

**Comment by aboe76** [comment]
see pillar.example: line 80
https://github.com/saltstack-formulas/php-formula/blob/master/pillar.example#L80

**Comment by gravyboat** [comment]
I'm going to close this one out, @RyPeck feel free to re-open if you don't think this solves it.
