### ISSUE TITLE
php.ng doesn't use PPA

### ISSUE THREAD

**Issue by robholmes** [saltstack-formulas/php-formula#36]
From what I can see, NG doesn't use the options of **use_ppa** and **ppa_name**.

Ideally I'd like to do this, to install PHP 5.6.7 from Ondřej Surý's excellent repo:

    php:
      # Use ppa instead the default repository (only Debian family)
      use_ppa: True
      # Set the ppa name (valid only if use_ppa is not none)
      ppa_name: 'ondrej/php5-5.6'

Can anyone help me please? I'm a bit new to Salt so excuse me if I'm being dumb, or if there is a better way that I'm not seeing.

I've got an inkling that maybe I could do something within the lookup.pkgs section of the pillar, but I have no idea how, so if anyone can give me an example I'd be really grateful.

**Comment by Seldaek** [comment]
I pushed a fix for this in my fork in case you want to give it a shot but hopefully it'll be merged here soon enough
