### ISSUE TITLE
Fork out php.ng formula

### ISSUE THREAD

**Issue by puneetk** [saltstack-formulas/php-formula#46]
Can we move the php.ng formula out to its on repo instead of keeping it in the php-formula ? 
or we can move the php-formula out to php-simple formula or something less confusing then having two formulas in one dir.

**Comment by gravyboat** [comment]
I honestly don't think we can. There's no explanation regarding what the ng formulas really are, and having two repos would be super confusing. Imagine if you looked at the php-ng formula before the normal php one as a new user. I'd give salt the middle finger at that point.

**Comment by puneetk** [comment]
well ok then @gravyboat

**Comment by RyPeck** [comment]
Perhaps when PHP6 comes out we can have a php6-formula? I imagine package names and other items might be a changing once that rolls out...

**Comment by iggy** [comment]
I like this idea in principle. We definitely need to think through how it's done so as to reduce confusing users (and possibly scaring them off).

Possibly a separate organization for them (saltstack-advanced-formulas or something).

Or label them well enough to point out that beginners should look at the non-"ng" formulas first.

**Comment by puneetk** [comment]
we could make it php-simple-formula in the saltstack-formula org, that will suffice
