### ISSUE TITLE
php.ng use_ppa doesnt work as expected

### ISSUE THREAD

**Issue by cybacolt** [saltstack-formulas/php-formula#61]
[merged PR](https://github.com/saltstack-formulas/php-formula/commit/6e6756a9f77b9401f0acbf15019689580866a59b) in reference to https://github.com/saltstack-formulas/php-formula/issues/36 checks use_ppa for its absence, but does not check value.

if you set use_ppa: False, it installs the ppa anyway.

**Comment by gravyboat** [comment]
It's checking for the existence of the `use_ppa` value at all so I can see how this would be problematic, @seldaek concerns over changing this to a default set of False and then checking for False? This is in relation to #38.

**Comment by gravyboat** [comment]
@cybacolt If you want to prep a PR to resolve this for a default setting of False, and then the corrected check I'd be happy to merge it in if @Seldaek doesn't have any concerns.

**Comment by cybacolt** [comment]
@gravyboat @Seldaek hopefully this will do the trick....

**Comment by Seldaek** [comment]
Seems good to me, I think this can be closed.
