### ISSUE TITLE
use_ppa does not add proper GPG key

### ISSUE THREAD

**Issue by hackel** [saltstack-formulas/php-formula#69]
When using use_ppa, no GPG is added for the PPA, therefore any states that need to install a package fail with `WARNING: The following packages cannot be authenticated!`  The only key that is currently present is for hhvm.  I got around this by just creating a separate state to add the PPA with the proper keyid:

```yaml
php56-repo:
  pkgrepo.managed:
    - ppa: ondrej/php5-5.6
    - keyid: E5267A6C
    - keyserver: keyserver.ubuntu.com
`

I don't know why this key isn't being pulled in automatically like it should, or whether the issue is specific to my setup (this is a new Ubuntu 14.04 instance).

**Comment by puneetk** [comment]
can u send it as a pull ?

**Comment by hackel** [comment]
The solution was actually a bit different from what I mentioned above, but it works!
