### ISSUE TITLE
PPA key is not successfully added on Ubuntu

### ISSUE THREAD

**Issue by VSpike** [saltstack-formulas/php-formula#88]
Took me a while to figure this one out!

The code added in https://github.com/saltstack-formulas/php-formula/pull/72 is broken. The **test** command needs a switch like -e or -f otherwise it always returns True, whether or not the file in /etc/apt/source.list.d exists.

This means the workaround to pre-add the repo ( apt-add-repository -y ppa:ondrej/php5-5.6 ) is never executed, meaning the next state (the pkgrepo.managed) fails due to the well-known Unicode bug.

I'll submit a PR with a possible fix shortly.

**Comment by gravyboat** [comment]
Going to close this since #89 was merged.
