### ISSUE TITLE
Ubuntu PPA must switch to main repo

### ISSUE THREAD

**Issue by johnccfm** [saltstack-formulas/php-formula#90]
The PHP 5.6 PPA is now deprecated and will generate deprecation warnings when updating. It seems like the only PPA that will be valid from now on is:

https://launchpad.net/~ondrej/+archive/ubuntu/php

This currently contains 5.5, 5.6 and 7.0. It seems that on Ubuntu 14.04, the following packages exist, for example for php-cli:-
- **php5-cli** - Ubuntu default version (5.5)
- **php5.5-cli** - PPA version 5.5
- **php5.6-cli** - PPA version 5.6
- **php7.0-cli** - PPA version 7.0
- **php-cli** - PPA version that resolves to version 7.0

It probably makes sense to default the PPA name to this one and make sure that the Jinja maps are updated to resolve this sensibly. Last time I tried, they didn't seem to work for version 7.0 so this may be an opportunity to resolve this too.

**Comment by johnccfm** [comment]
Here's the warning text that shows  up when configuring php5-common in aptitude.

> 
> This PPA is deprecated!
> 
> Please note that this PPA is deprecated and it's being replaced with ppa:ondrej/php that contains co-installable versions of PHP 5.5, PHP 5.6 and PHP 7.0.
> 
> This PPA will reach end of life at the end of June 2016, and you have to replace it with the new centralized PHP PPA.
> 
> To add the new PPA, do:
> 
> sudo LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php
> 
> sudo apt-get update
> 
> And the install correct PHP version:
> 
> sudo apt-get install php7.0 # for PHP 7.0
> 
> sudo apt-get install php5.6 # for PHP 5.6
> 
> sudo apt-get install php5.5 # for PHP 5.5
> 
> The packages for extensions contain modules for all supported PHP versions and can be installed with (f.e. xdebug and APCu):                                                                                                                   
> 
> sudo apt-get install php-xdebug php-apcu

**Comment by alxwr** [comment]
PHP 7 landed in 16.04.
