### ISSUE TITLE
php state mention unexistent state

### ISSUE THREAD

**Issue by genuss** [saltstack-formulas/php-formula#99]
While updating my internal php-formula just mentioned ``php/init.sls`` includes ``php.dotdeb`` which is not existent here.
I suppose inclusion should be removed or state added:)

**Comment by aboe76** [comment]
@bogdanr could you take a look I think the php.dotdeb was introduced by your pr...

**Comment by babilen** [comment]
Introduced in https://github.com/saltstack-formulas/php-formula/pull/77

**Comment by genuss** [comment]
I hate to tell you this but still there no ``php.dotdeb`` state!

**Comment by velikanov** [comment]
👍

**Comment by babilen** [comment]
We might just want to drop it from init.

**Comment by velikanov** [comment]
yeah, that would be the best solution
